# this workflow checks if log.Fatal/Fatalf has been used in the program
# which can prevent some test cases from being possible.

name: Check_Fatal

on:
  pull_request:

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'
        check-latest: true

    - name: Check for usage of fatal in source
      run: |
        set -e
        if find -name "*.go" -exec grep -Hn "Fatal" {} +; then
            echo "::error ::Found disallow Fatal*() calls"
            exit 1
        fi
