# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'
        check-latest: true

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: go test -vet=off -v ./...

  stats:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: run cloc
      run: |
        sudo apt install cloc
        cloc . > cloc.txt
        echo #### > cloc.md
        echo '```' > cloc.md 
        cat cloc.txt > cloc.md
        echo '```' > cloc.md
    - name: push changes
      run : |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add cloc.md
        git commit -m "updating cloc output [ci skip]" || echo 'no changes'
        git push

  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Check for usage of fatal in source
      run: |
        set -e
        echo "Checking for disallowed usage of testing.T methods..."
        if find . -name "*.go" -exec grep -EIHn '\b\w+\s*\.\s*(Errorf|Error|Fatalf|Fatal|FailNow|Fail)\s*\(' {} +; then
            echo "::error ::Found disallowed testing.T method calls"
            exit 1
        fi
